#clean out mesquite jargan from nexus file if nexus file was generated by mesquite
from io import StringIO

def clean_nexus(file_path):
    """Extract only the CHARACTERS block from a Mesquite-style NEXUS file."""
    with open(file_path, "r") as f:
        lines = f.readlines()
    
    keep = []
    inside_characters = False

    for line in lines:
        line_lower = line.strip().lower()
        if line_lower.startswith("begin characters"):
            inside_characters = True
        elif line_lower == "end;" and inside_characters:
            keep.append(line)
            break  # stop after CHARACTERS block ends
        elif inside_characters:
            keep.append(line)

    if not keep:
        raise ValueError(f"No CHARACTERS block found in {file_path}")
    
    return StringIO("".join(keep))